spring:
  profiles:
    active: mariadb

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/bobmuckda?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: sideproject
    password: qlalfqjsgh
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql : true
        format_sql : true
logging:
  level:
    org:
      hibernate:
        type:
          dsescriptor:
            sql : trace
server:
  port: 8080

#  Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행하겠다는 것입니다.
#  여기서 ${job.name:NONE}을 보면 :를 사이에 두고 좌측에 job.name이, 우측에 NONE이 있는데요.
#  이 코드의 의미는 job.name이 있으면 job.name값을 할당하고, 없으면 NONE을 할당하겠다는 의미입니다.
#  중요한 것은! spring.batch.job.names에 NONE이 할당되면 어떤 배치도 실행하지 않겠다는 의미입니다.
#  즉, 혹시라도 값이 없을때 모든 배치가 실행되지 않도록 막는 역할입니다.
